all:
	g++ -std=c++11 -o shared_pointers.o -c shared_pointers.cpp
	g++ -std=c++11 -o threads.o -c threads.cpp
	g++ -std=c++11 -o shared_data.o -c shared_data.cpp
	g++ -std=c++11 -o producer_consumer.o -c producer_consumer.cpp
	g++ -std=c++11 -o future.o -c future.cpp
	g++ -std=c++11 -o packaged_tasks.o -c packaged_tasks.cpp
	g++ -std=c++11 -o asyncs.o -c asyncs.cpp
clean:
	rm *.o
