all:
	g++ --std=c++11 -o time.o -c time.cpp
	g++ --std=c++11 -o type_functions.o -c type_functions.cpp
	g++ --std=c++11 -o type_predicates.o -c type_predicates.cpp
	g++ --std=c++11 -o tuples.o -c tuples.cpp
clean:
	rm *.o
