all:
	g++ -std=c++11 -o std_strings.o -c std_strings.cpp
	g++ -std=c++11 -o streamio.o -c streamio.cpp
	g++ -std=c++11 -o vectors.o -c vectors.cpp
	g++ -std=c++11 -o range_check.o -c range_check.cpp
	g++ -std=c++11 -o lists.o -c lists.cpp
	g++ -std=c++11 -o maps.o -c maps.cpp
	c++ -std=c++11 -o unordered_maps.o -c unordered_maps.cpp
clean:
	rm *.o
