# Compiles all cpp files to object code. Doesn't link.
all:
	g++ -std=c++11 -o complex.o -c complex.cpp
	g++ -std=c++11 -o examples.o -c examples.cpp
	g++ -std=c++11 -o less_than.o -c less_than.cpp
	g++ -std=c++11 -o shape.o -c shape.cpp
	g++ -std=c++11 -o variadic_template.o -c variadic_template.cpp
clean:
	rm *.o
