# Compiles all cpp files to object code, but doesn't link
all:
	g++ -o complex.o -c complex.cpp
	g++ -o examples.o -c examples.cpp
	g++ -o less_than.o -c less_than.cpp
	g++ -o shape.o -c shape.cpp
	g++ -o variadic_template.o -c variadic_template.cpp
